fix build on Arch Linux
qtimageformats/src/plugins/imageformats/jp2/qjp2handler.cpp:844:41:
error: no declaration of «pow»
  844 |     const double jasperRate = minRate + pow((double(quality) / double(maxQuality)), 2) * maxRate;

Change-Id: I085996c2db2251903b2a3e52e6e648831637c8f9
(cherry picked from commit 704868db61be1542c2d9e2b75ead00c45c56cc36)
Reviewed-by: Shawn Rutledge <shawn.rutledge@qt.io>