QTiffHandler: fix build with GCC 13's support for FP16
Conversion must be explicit from float.

qtiffhandler.cpp:963:30: error: converting to ‘qfloat16::NativeType’ {aka ‘_Float16’} from ‘float’ with greater conversion rank [-Werror]

Change-Id: Ide4dbd0777a44ed0870efffd17390a0e86f1fd7e
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>
(cherry picked from commit d2b72c842a1e3a5a7ca5a06c88e0ae12a988118b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>